"""Signal domain entities."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import uuid


class SignalSource(Enum):
    """Signal origin source."""
    TELEGRAM = "telegram"    # External Telegram channel
    INTERNAL = "internal"    # Generated by our own analysis
    HYBRID = "hybrid"        # Combination of both


class SignalQuality(Enum):
    """Signal quality assessment."""
    EXCELLENT = "excellent"  # High confidence, all checks passed
    GOOD = "good"            # Good quality, minor concerns
    ACCEPTABLE = "acceptable"  # Acceptable but not ideal
    POOR = "poor"            # Low quality, high risk
    REJECTED = "rejected"    # Failed validation


@dataclass
class Signal:
    """Trading signal entity.
    
    Represents a trading signal from any source (Telegram, internal analysis, etc).
    Contains all information needed to evaluate and potentially execute the signal.
    """
    # Core signal data
    symbol: str
    direction: str  # "buy" or "sell"
    entry_price: float
    stop_loss: float
    take_profit: float
    
    # Metadata
    source: SignalSource
    timestamp: datetime = field(default_factory=lambda: datetime.now())
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    
    # Optional context
    raw_message: str = ""         # Original message text
    source_id: str = ""           # Message ID or source identifier
    confidence_score: float = 0.5  # 0.0 to 1.0
    quality: SignalQuality = SignalQuality.ACCEPTABLE
    
    # Analysis results (populated after evaluation)
    validation_result: dict = field(default_factory=dict)
    cross_check_result: dict = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate signal parameters."""
        if self.entry_price <= 0:
            raise ValueError(f"Invalid entry price: {self.entry_price}")
        if self.stop_loss <= 0:
            raise ValueError(f"Invalid stop loss: {self.stop_loss}")
        if self.take_profit <= 0:
            raise ValueError(f"Invalid take profit: {self.take_profit}")
        if self.direction not in ["buy", "sell"]:
            raise ValueError(f"Invalid direction: {self.direction}")
        if not 0.0 <= self.confidence_score <= 1.0:
            raise ValueError(f"Confidence must be 0-1: {self.confidence_score}")
    
    def risk_reward_ratio(self) -> float:
        """Calculate risk:reward ratio."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        return reward / risk if risk > 0 else 0.0
    
    def risk_points(self) -> float:
        """Risk in price points."""
        return abs(self.entry_price - self.stop_loss)
    
    def reward_points(self) -> float:
        """Potential reward in price points."""
        return abs(self.take_profit - self.entry_price)
    
    def is_buy(self) -> bool:
        return self.direction.lower() == "buy"
    
    def is_sell(self) -> bool:
        return self.direction.lower() == "sell"
    
    def is_from_telegram(self) -> bool:
        return self.source == SignalSource.TELEGRAM
    
    def is_high_quality(self) -> bool:
        """Check if signal quality is good enough."""
        return self.quality in [SignalQuality.EXCELLENT, SignalQuality.GOOD]
    
    def age_seconds(self) -> float:
        """Signal age in seconds."""
        return (datetime.now() - self.timestamp).total_seconds()
    
    def __repr__(self) -> str:
        direction_emoji = "📈" if self.is_buy() else "📉"
        quality_emoji = {
            SignalQuality.EXCELLENT: "⭐⭐⭐",
            SignalQuality.GOOD: "⭐⭐",
            SignalQuality.ACCEPTABLE: "⭐",
            SignalQuality.POOR: "⚠️",
            SignalQuality.REJECTED: "❌"
        }.get(self.quality, "❓")
        
        return (
            f"Signal({direction_emoji} {self.symbol} {self.direction.upper()} "
            f"@ {self.entry_price} RR:{self.risk_reward_ratio():.1f} "
            f"{quality_emoji} {self.source.value})"
        )
